### ISSUE TITLE
Using `mirroredInertia` mirrors also the mass value, copying the value from the XML file

### ISSUE THREAD

**Issue by HosameldinMohamed** [robotology/simmechanics-to-urdf#58]
If I put in the YAML file the following lines:

```yaml
assignedMasses:
  l_upper_arm : 1.8703
  r_upper_arm : 1.8703
```
Then:

```yaml
mirroredInertia:
  - mirroredLink: l_upper_arm
    originalLink: r_upper_arm
    simmetryReferenceLink: root_link
    symmetryPlane: xz
```

And the values of `l_upper_arm` and `r_upper_arm` originally in the XML file are `1.6756` and `1.67729`, respectively.

The result in the URDF file is:

`l_upper_arm`: `1.67729`
`r_upper_arm`: `1.8703`

So it seems that the value of `l_upper_arm` got the original mass of `r_upper_arm` in the XML file.

Is that a desired behavior to mirror also the mass? If yes, then maybe it's better to mirror the new value in `assignedMasses`.
